### ISSUE TITLE
annotate HAB_Field dataset v1

### ISSUE THREAD

**Issue by ktl014** [hab-spc/hab-ml#20]
Overview:
As an annotator, I need to know what time periods to annotate for the HAB_Field dataset. The time periods should be days, where there is a high count from SCCOOS. The time periods should also be centered 1 hour around Melissa's sample time. In other words, to get the high counts, we need to sort her counts in ascending order and select the first 10-20 dates. The date range should be from May 2016 to present.

Prior steps:
- Read through [SPC labeling guide](https://docs.google.com/presentation/d/1XiCrBqRd60BmN-oIXmw8cYN5qIH8kGhd3VPIKWYP5Bc/edit?usp=sharing). 
- Determine validation procedure with Melissa
- Make SPC labeling account
- Create online google sheets for data collection records (store in HAB_data google drive folder)

Goal: Annotate data 

Due Date [DELAYED]: ~5/22/19 6 PM [Latest 5/23/19 6 PM]~
~Need the gtruth to present benchmark analysis data on Friday meeting (5/24) -K.Le~

Defintion of Done (DoD): Excell sheet that should be categorized by date and time centered around Melissa's sample time.  Excell sheet will be used to provide information for eng team to get the labels.

**Comment by ktl014** [comment]
Prorocentrum Michans:
2017-04-10 09:28:00 - 10:28:00 (Mel's smpl time: 9:53:00)
2017-04-03 09:34:00 - 10:34:00 (10:04:00)
2017-03-27 10:10:00 - 11:10:00 (10:40:00)
2017-04-17 09:51:00 - 10:51:00 (10:21:00)
2017-04-24 09:36:00 - 10:36:00 (10:06:00)
2017-03-20 09:23:00 - 10:23:00 (9:53:00)

**Comment by ktl014** [comment]
@sarahstrang @MelansonKayani this is basically the first task I mentioned in our kickoff meeting. I provided the list of dates and specified times to label for the prorocentrum michans above. 

Let me know if you received this msg and are ready to go, since this is the first time we're using github. Good luck!!

**Comment by sarahstrang** [comment]
I am ready to go! Excited for tomorrow.
